# Generated by Django 5.0.4 on 2024-05-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.profile'),
        ),
    ]
