# Generated by Django 5.0.4 on 2024-05-15 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_collections_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.profile'),
        ),
        migrations.AlterField(
            model_name='pins',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.collections'),
        ),
    ]
