# Generated by Django 5.0.4 on 2024-05-15 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_collections_author_alter_pins_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.collections'),
        ),
    ]
