# Generated by Django 5.0.4 on 2024-06-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
