# Generated by Django 5.0.4 on 2024-06-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_profile_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_online',
        ),
    ]
