# Generated by Django 5.0.4 on 2024-06-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
